name: Hello world
author: JCFlores93
description: Some description
inputs:
  who-to-greet:
    description: 'Who to greet'
    required: true
    default: JCFlores93
outputs:
  time:
    description: "The greeting time"
runs:
  using: "node12"
  main: "index.js"